spring:
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        jedis:
          pool:
            max-active: 100
            max-idle: 10
            max-wait: 100000
        timeout: 5000